### ISSUE TITLE
Error building a linc project

### ISSUE THREAD

**Issue by darmie** [snowkit/linc#10]
I am trying to bind libuv with haxe using linc template. I got this error when I ran this test

```
Test.cpp
./src/Test.cpp(102): error C2039: 'RegisterClassA': is not a member of 'hx'
C:/HaxeToolkit/haxe/lib/hxcpp/3,2,205/include\hx/Boot.h(7): note: see declaration of 'hx'
./src/Test.cpp(102): error C2660: 'RegisterClassA': function does not take 2 arguments
```

The Test code:

``` hx
import uv.Loop;
import uv.Loop.Loop_t;

class Test {

    static function main() {
        var loop_t:Loop_t = Loop.create();
        Loop.init(loop_t);

    }

}
```

**Comment by ruby0x1** [comment]
This comes from the order in which windows.h is included. Typically you need to make sure hxcpp.h is included first before anything else (especially things that might include Windows.h, as this is where that comes from).
