### ISSUE TITLE
Getting data from struct pointers in haxe code

### ISSUE THREAD

**Issue by Aidan63** [snowkit/linc#12]
Hello!
I've been working on externs for [Discord's RPC library](https://github.com/discordapp/discord-rpc). It's all working fine except for this last part. One of the callbacks returns a const pointer to a struct and I'm having trouble accessing the data in the struct from haxe.

This is the class I've created in haxe to represent the Discord struct.
```haxe
@:include('linc_discord_rpc.h')
@:native('DiscordJoinRequest')
@:structAccess
private extern class ExternJoinRequst
{
    public var userId : String;
    public var username : String;
    public var avatar : String;
}
```
This is the struct definition in Discord's header file.
```c
typedef struct DiscordJoinRequest {
    const char* userId;
    const char* username;
    const char* avatar;
} DiscordJoinRequest;
```
This is the static function callback where I'm trying to access the data.
```haxe
private static inline function _onRequest(_data : RawConstPointer<ExternJoinRequst>) : Void {
    var data = ConstPointer.fromRaw(_data).value;
    trace(data.userId, data.username, data.avatar);
}
```
The trace function returns `true,true,true` not the data I'd expect. Is fromRaw the correct way to do this? Looking through the haxe cpp api it seems to be the way to convert a raw pointer to something haxe can use. Is this correct, or am I missing something?
Repo containing all of the code can be found [here](https://github.com/Aidan63/haxe-discord_rpc-externs).

Thanks for any help!

**Comment by ruby0x1** [comment]
Let's see if @hughsando has any thoughts in the meantime.

**Comment by hughsando** [comment]
Is `public var userId : String;` actually a haxe String, or would `cpp.ConstCharStar` be a better description?

**Comment by Aidan63** [comment]
That did it! Makes a lot of sense now that I think about it since it's an extern class. Thanks for the help!
