### ISSUE TITLE
linc_yoga - Facebook Yoga Library

### ISSUE THREAD

**Issue by darmie** [snowkit/linc#13]
I have created a linc library for the Facebook Yoga library, so far all tests are passing.

Kindly review, and hopefully add it to the list of linc libraries.  

It's available here: [linc_yoga](https://github.com/darmie/linc_yoga)

Thanks.

**Comment by anissen** [comment]
I've added your library to the list of [community created _linc_ libraries](https://github.com/anissen/awesome-snowkit/blob/master/README.md#community-created). Thanks!

**Comment by darmie** [comment]
Thanks @anissen
