### ISSUE TITLE
ffmpeg & quicktime

### ISSUE THREAD

**Issue by delahee** [snowkit/linc#5]
Hi, 
I have an opening to work with big video content, in order to get best performance, I am thinking to build a linc style ffmpeg and qtime libs. This may take months since I am in no hurry. If you are interested, please ping so that I know to keep you posted. I'll try to follow linc conventions if I finalize something Or if you feel there are ressources I should see.

bye !

**Comment by ivodopiviz** [comment]
ping

**Comment by delahee** [comment]
yep progress has stalled ( https://github.com/delahee/linc_ffmpeg ) because I have different priorities this month. Basically video is working great, I have been struggling with callbacks a looot because nativegen is still too experimental, I am finishing audio samples which are complicated because many callbacks (sigh). Hugh have improved stability and native interaction a lot but there were some blocking walls so I had to defocus not to get bored by compile walls. I have scheduled a more focused session early june so I kinda of hope to have a first working batch of samples around this time period.

++

**Comment by ivodopiviz** [comment]
It's OK, I'd just like to know if this eventually gets more mature, since there aren't that many updated, sane options for video playback in Haxe ATM. Coincidentally, I was looking for a linc example that used binary libs instead of source, so thanks :)

**Comment by delahee** [comment]
The library stub is quite complete enough. let's close this :)
