### ISSUE TITLE
#include <hxcpp.h>placement problem

### ISSUE THREAD

**Issue by Yanrishatum** [snowkit/linc#9]
I'm not sure why, but with newest HXCPP there's a warning following with errors while compiling:

```
E:/HaxeToolkit/haxe/lib/linc_opengl/git//linc/linc_opengl.cpp(3) : warning C4627: '#include "./linc_opengl.h"': skipped when looking for precompiled header use
```

This happens because all linc_ libraries include it's own headers first, and then `hxcpp.h`.  
Changing order to `hxcpp.h` first and then other hreaders in `cpp` files fixes problem. This include should be placed even before `#ifndef ...`.  
Got this issue on Windows and Mac.  
Creating issue here, because it influence all linc libraries.

**Comment by ruby0x1** [comment]
All repos have been updated to have hxcpp first!

p.s I never got any warnings/errors on mac from this in particular (with 3.3.x, 3.4.x so far, and I'm on 3.4 nightly atm and it looks fine still).
